// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.25.0

package models

import (
	"database/sql/driver"
	"fmt"

	"github.com/jackc/pgx/v5/pgtype"
)

type AccessPermissionType string

const (
	AccessPermissionTypeADMIN  AccessPermissionType = "ADMIN"
	AccessPermissionTypeMEMBER AccessPermissionType = "MEMBER"
)

func (e *AccessPermissionType) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = AccessPermissionType(s)
	case string:
		*e = AccessPermissionType(s)
	default:
		return fmt.Errorf("unsupported scan type for AccessPermissionType: %T", src)
	}
	return nil
}

type NullAccessPermissionType struct {
	AccessPermissionType AccessPermissionType `json:"accessPermissionType"`
	Valid                bool                 `json:"valid"` // Valid is true if AccessPermissionType is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullAccessPermissionType) Scan(value interface{}) error {
	if value == nil {
		ns.AccessPermissionType, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.AccessPermissionType.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullAccessPermissionType) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.AccessPermissionType), nil
}

type ModelType string

const (
	ModelTypeGpt35Turbo          ModelType = "gpt-3.5-turbo"
	ModelTypeGpt35Turbo16k       ModelType = "gpt-3.5-turbo-16k"
	ModelTypeGpt4                ModelType = "gpt-4"
	ModelTypeGpt432k             ModelType = "gpt-4-32k"
	ModelTypeCommand             ModelType = "command"
	ModelTypeCommandLight        ModelType = "command-light"
	ModelTypeCommandNightly      ModelType = "command-nightly"
	ModelTypeCommandLightNightly ModelType = "command-light-nightly"
)

func (e *ModelType) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = ModelType(s)
	case string:
		*e = ModelType(s)
	default:
		return fmt.Errorf("unsupported scan type for ModelType: %T", src)
	}
	return nil
}

type NullModelType struct {
	ModelType ModelType `json:"modelType"`
	Valid     bool      `json:"valid"` // Valid is true if ModelType is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullModelType) Scan(value interface{}) error {
	if value == nil {
		ns.ModelType, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.ModelType.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullModelType) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.ModelType), nil
}

type ModelVendor string

const (
	ModelVendorOPENAI ModelVendor = "OPEN_AI"
	ModelVendorCOHERE ModelVendor = "COHERE"
)

func (e *ModelVendor) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = ModelVendor(s)
	case string:
		*e = ModelVendor(s)
	default:
		return fmt.Errorf("unsupported scan type for ModelVendor: %T", src)
	}
	return nil
}

type NullModelVendor struct {
	ModelVendor ModelVendor `json:"modelVendor"`
	Valid       bool        `json:"valid"` // Valid is true if ModelVendor is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullModelVendor) Scan(value interface{}) error {
	if value == nil {
		ns.ModelVendor, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.ModelVendor.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullModelVendor) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.ModelVendor), nil
}

type PromptFinishReason string

const (
	PromptFinishReasonDONE  PromptFinishReason = "DONE"
	PromptFinishReasonERROR PromptFinishReason = "ERROR"
	PromptFinishReasonLIMIT PromptFinishReason = "LIMIT"
)

func (e *PromptFinishReason) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = PromptFinishReason(s)
	case string:
		*e = PromptFinishReason(s)
	default:
		return fmt.Errorf("unsupported scan type for PromptFinishReason: %T", src)
	}
	return nil
}

type NullPromptFinishReason struct {
	PromptFinishReason PromptFinishReason `json:"promptFinishReason"`
	Valid              bool               `json:"valid"` // Valid is true if PromptFinishReason is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullPromptFinishReason) Scan(value interface{}) error {
	if value == nil {
		ns.PromptFinishReason, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.PromptFinishReason.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullPromptFinishReason) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.PromptFinishReason), nil
}

type ApiKey struct {
	CreatedAt     pgtype.Timestamptz `json:"createdAt"`
	DeletedAt     pgtype.Timestamptz `json:"deletedAt"`
	Name          string             `json:"name"`
	ID            pgtype.UUID        `json:"id"`
	ApplicationID pgtype.UUID        `json:"applicationId"`
	IsInternal    bool               `json:"isInternal"`
}

type Application struct {
	CreatedAt   pgtype.Timestamptz `json:"createdAt"`
	UpdatedAt   pgtype.Timestamptz `json:"updatedAt"`
	DeletedAt   pgtype.Timestamptz `json:"deletedAt"`
	Description string             `json:"description"`
	Name        string             `json:"name"`
	ID          pgtype.UUID        `json:"id"`
	ProjectID   pgtype.UUID        `json:"projectId"`
}

type Project struct {
	CreatedAt   pgtype.Timestamptz `json:"createdAt"`
	UpdatedAt   pgtype.Timestamptz `json:"updatedAt"`
	DeletedAt   pgtype.Timestamptz `json:"deletedAt"`
	Name        string             `json:"name"`
	Description string             `json:"description"`
	Credits     pgtype.Numeric     `json:"credits"`
	ID          pgtype.UUID        `json:"id"`
}

type ProjectInvitation struct {
	CreatedAt  pgtype.Timestamptz   `json:"createdAt"`
	UpdatedAt  pgtype.Timestamptz   `json:"updatedAt"`
	Email      string               `json:"email"`
	Permission AccessPermissionType `json:"permission"`
	ID         pgtype.UUID          `json:"id"`
	ProjectID  pgtype.UUID          `json:"projectId"`
}

type PromptConfig struct {
	CreatedAt                 pgtype.Timestamptz `json:"createdAt"`
	DeletedAt                 pgtype.Timestamptz `json:"deletedAt"`
	UpdatedAt                 pgtype.Timestamptz `json:"updatedAt"`
	ModelType                 ModelType          `json:"modelType"`
	ModelVendor               ModelVendor        `json:"modelVendor"`
	Name                      string             `json:"name"`
	ProviderPromptMessages    []byte             `json:"providerPromptMessages"`
	ExpectedTemplateVariables []string           `json:"expectedTemplateVariables"`
	ModelParameters           []byte             `json:"modelParameters"`
	ID                        pgtype.UUID        `json:"id"`
	ApplicationID             pgtype.UUID        `json:"applicationId"`
	IsDefault                 bool               `json:"isDefault"`
	IsTestConfig              bool               `json:"isTestConfig"`
}

type PromptRequestRecord struct {
	DeletedAt              pgtype.Timestamptz `json:"deletedAt"`
	CreatedAt              pgtype.Timestamptz `json:"createdAt"`
	StartTime              pgtype.Timestamptz `json:"startTime"`
	FinishTime             pgtype.Timestamptz `json:"finishTime"`
	FinishReason           PromptFinishReason `json:"finishReason"`
	RequestTokensCost      pgtype.Numeric     `json:"requestTokensCost"`
	ResponseTokensCost     pgtype.Numeric     `json:"responseTokensCost"`
	ErrorLog               pgtype.Text        `json:"errorLog"`
	DurationMs             pgtype.Int4        `json:"durationMs"`
	ResponseTokens         int32              `json:"responseTokens"`
	RequestTokens          int32              `json:"requestTokens"`
	ID                     pgtype.UUID        `json:"id"`
	PromptConfigID         pgtype.UUID        `json:"promptConfigId"`
	ProviderModelPricingID pgtype.UUID        `json:"providerModelPricingId"`
	IsStreamResponse       bool               `json:"isStreamResponse"`
}

type PromptTestRecord struct {
	CreatedAt             pgtype.Timestamptz `json:"createdAt"`
	Response              string             `json:"response"`
	VariableValues        []byte             `json:"variableValues"`
	ID                    pgtype.UUID        `json:"id"`
	PromptRequestRecordID pgtype.UUID        `json:"promptRequestRecordId"`
}

type ProviderKey struct {
	CreatedAt       pgtype.Timestamptz `json:"createdAt"`
	ModelVendor     ModelVendor        `json:"modelVendor"`
	EncryptedApiKey string             `json:"encryptedApiKey"`
	ID              pgtype.UUID        `json:"id"`
	ProjectID       pgtype.UUID        `json:"projectId"`
}

type ProviderModelPricing struct {
	CreatedAt        pgtype.Timestamptz `json:"createdAt"`
	ActiveFromDate   pgtype.Date        `json:"activeFromDate"`
	ActiveToDate     pgtype.Date        `json:"activeToDate"`
	ModelType        ModelType          `json:"modelType"`
	ModelVendor      ModelVendor        `json:"modelVendor"`
	InputTokenPrice  pgtype.Numeric     `json:"inputTokenPrice"`
	OutputTokenPrice pgtype.Numeric     `json:"outputTokenPrice"`
	TokenUnitSize    int32              `json:"tokenUnitSize"`
	ID               pgtype.UUID        `json:"id"`
}

type UserAccount struct {
	CreatedAt   pgtype.Timestamptz `json:"createdAt"`
	DisplayName string             `json:"displayName"`
	Email       string             `json:"email"`
	FirebaseID  string             `json:"firebaseId"`
	PhoneNumber string             `json:"phoneNumber"`
	PhotoUrl    string             `json:"photoUrl"`
	ID          pgtype.UUID        `json:"id"`
}

type UserProject struct {
	CreatedAt  pgtype.Timestamptz   `json:"createdAt"`
	UpdatedAt  pgtype.Timestamptz   `json:"updatedAt"`
	Permission AccessPermissionType `json:"permission"`
	UserID     pgtype.UUID          `json:"userId"`
	ProjectID  pgtype.UUID          `json:"projectId"`
}
